Dim sob
set sob = WScript.CreateObject("Wscript.Shell")

Function GenerateComp( fname, fullstring, path )
	dim cmd
'	path = "..\"
  cmd = "Cmd /c copy /b /y "+fullstring+" "+path+fname+".html"
	'sob.popup cmd
	sob.run(cmd)
End Function

source_dlsg = "..\..\dlsg\pieces\"
source_local = ".\"
build_dest = "e:\iis\kic.com\"

'system product family
fname = "kic"
softprod = "kic"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + "snip-kic.html+"
fullstring = fullstring + source_dlsg + softprod + "\kic-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\fleet-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-13.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-14.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-15.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "kic-bookedge"
softprod = "kic"
lpath = ".\be\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-doc.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "kic-click-mini"
softprod = "kic"
lpath = ".\click_click-mini\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-clickmini.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-doc.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
'fname = "kic-bookclick"
fname = "kic-click"
softprod = "kic"
lpath = ".\click_click-mini\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-click.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-doc.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "kic-bookeye4v1"
softprod = "kic"
lpath = ".\be4\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "kic-bookeye4v2"
softprod = "kic"
lpath = ".\be4\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "kic-bookeye4v3"
softprod = "kic"
lpath = ".\be4\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "kic-bookeye3r2"
softprod = "kic"
lpath = ".\be32\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be3r2.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\fleet-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-13.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-14.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-15.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "kic-widetek25"
softprod = "kic"
lpath = ".\wt25\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-wt25.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-09.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\fleet-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-10.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-11.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-12.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-13.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-14.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-15.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-kic-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest