Dim sob
set sob = WScript.CreateObject("Wscript.Shell")

Function GenerateComp( fname, fullstring, path )
	dim cmd
'	path = "..\"
	cmd = "Cmd /c copy /b /y "+fullstring+" "+path+fname+".html"
	'sob.popup cmd
	sob.run(cmd)
End Function

source_dlsg = "..\..\dlsg\pieces\"
source_local = ".\"
build_dest = "e:\iis\kic.com\"

'system product family
fname = "opus-freeflow"
softprod = "ff"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + "snip-" + softprod + ".html+"
fullstring = fullstring + source_dlsg + softprod + "\ff-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "opus-freeflow-bookedge"
softprod = "ff"
lpath = ".\be\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-doc.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "opus-freeflow-bookeye4v1"
softprod = "ff"
lpath = ".\be4v1\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "opus-freeflow-bookeye4v2"
softprod = "ff"
lpath = ".\be4v2\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "opus-freeflow-bookeye4v3"
softprod = "ff"
lpath = ".\be4v3\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "opus-freeflow-bookeye3r2"
softprod = "ff"
lpath = ".\be32\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-be3r2.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "opus-freeflow-widetek25"
softprod = "ff"
lpath = ".\wt25\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-wt25.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest

'system product
fname = "opus-freeflow-widetek36ds"
softprod = "ff"
lpath = ".\wt36ds\"
fullstring = source_local + "header.html+navbar.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-wt36.html+"
fullstring = fullstring + source_dlsg + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + source_dlsg + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + source_dlsg + softprod + "\snip-label.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-start.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-overview.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-features.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-techspec.html+"
fullstring = fullstring + source_dlsg + lpath + "snip-opus-doc.html+"
fullstring = fullstring + source_dlsg + "snip-product-compliance.html+"
fullstring = fullstring + source_dlsg + "snip-product-tabs-end.html+"
fullstring = fullstring + source_local + "footer.html"
GenerateComp fname, fullstring, build_dest